### ISSUE TITLE
[PE-D][Tester C] No error checking in Delete-Expense for negative index

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113T-W11-1/tp#176]
![image.png](https://raw.githubusercontent.com/nshian/ped/main/files/571ec218-c653-401b-9040-7fc7d279fe51.png)

When the user inputs a negative index for the EXPENSE_NUMBER, the error message says that the input is of invalid syntax even though it is of perfectly valid syntax. Should have additional error checking for negative indexes and a different error message to display to the user so that they can be alerted to the type of mistake they are making.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: nshian/ped#7

**Comment by xzynos** [comment]
Not a bug.

The error message says that "The arguments entered are invalid".
