### ISSUE TITLE
Some comments/suggestions on your DG

### ISSUE THREAD

**Issue by okkhoy** [AY2223S1-CS2113T-W11-1/tp#211]
1. Please pay attention to this and rectify the issue + remove the notification before the final version
![image](https://user-images.githubusercontent.com/1023494/198888005-95a1b1b3-2b9b-43d0-9d8c-ceac2b507772.png)

2. Pl. indicate that you are creating an expense here for clarity
![image](https://user-images.githubusercontent.com/1023494/198888335-3ebbfcd3-a2b2-4df0-a8ca-970e66d318ef.png)

3. This diagram is not adding any additional value to the text preceding it
![image](https://user-images.githubusercontent.com/1023494/198888408-8820aa00-62ff-48dc-b6bb-56d44df5c2e5.png)

4. Hmmm what diagram is this?
![image](https://user-images.githubusercontent.com/1023494/198888428-e5bb517a-a693-48e8-b5f6-ec52103ab6c5.png)

5. Abstract is written in curly braces `{abstract}`
![image](https://user-images.githubusercontent.com/1023494/198888484-61781e24-70e0-4aff-b45d-655a6f3f4b4b.png)

6. Better to spell out entirely to say this is the version in which the user story is implemented
![image](https://user-images.githubusercontent.com/1023494/198888599-ee11e7ed-90d7-476f-a0a1-fd7b70e13606.png)

**Comment by xzynos** [comment]
Thank you so much for your input professor. We will rectify the issues you have brought up.

Fang Jie
